### PR TITLE
Adding footprint Relay_DPDT_Omron_G5V-2.kicad_mod for Omron G5V-2 relay

### PR DESCRIPTION
**Pull request by ouinouin**
Omron footprint for G5V2 relay (passed KLC scripts), see PR for schematic : [https://github.com/KiCad/kicad-library/pull/1686](url)
I also made the 3d model from freecad 0.16 + step up converter , and I m ready to contribute the source + wrl model, but Relays_THT.3dshapes seems to be absent from kicad-packages3D , shall I add this folder while doing pull request for the 3dshape ? 

screenshot at 2017-10-05 13 15 38
screenshot at 2017-10-05 13 25 20

### CODE REVIEW

**Comment by jkriege2** [comment]
yes simply add that folder where required ... and I will have a closer look at this PR this evening.

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

very nice work! There are only very few small thing you need to change, before I can merge:
1. please add a pin1-marker to F.Fab (beveled corner) and F.Silks (additional corner):
2017-10-05 18_49_33-footprint editor no active library
2. please make pin1 rectangular
3. optional: move the VALUE to the side ...


Best,
JAN

**Comment by ouinouin** [comment]
Hi, Modification done according to your advices 
screenshot at 2017-10-05 21 49 11

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
