### PR TITLE
Added footprint for relays Schrack series RYII.

### PR DESCRIPTION
**Pull request by fred-maria**
3 footprints added for RYII series :
 - one for form C contact (pinning 3.2mm)
 - two for form A and form B contacts (pinning 5mm) as they have different pad numbers.

Dimensions from : http://www.farnell.com/datasheets/1719912.pdf

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
Thanks for the contribution. Please ensure that you follow the KLC (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). Here is an example of how a KLC-conformant relay may look:
2016-12-03 13_09_09-footprinteditor keine aktive bibliothek

Please change the following in your device:
1. add F.Fab layer with component outline
2. ensure Silkscreen is visible after putting the device on the PCB and that it does not overlap with the pads
3. If you have time: Please create symbols for the relays, as it is otherwise hard to use the footprints ,-)
4. anchor should be in the center of pin 1 (maybe A1 for your device?)
5. separate keywords by spaces, not comma.

there are also Pythonscripts that can be used to check these rules: https://github.com/KiCad/kicad-library-utils

cu
JAN

**Comment by fred-maria** [comment]
Hello,
I am on the way to fix the issues. Thanks for taking time to explain them and to point to the scripts that help check them.

BTW, I realized that I used the naming Form-A and Form-B to express a normally open (NO) and normally closed (NC) contact.
I can see the library contains 2 other relays with the following names: 
Relay_**SPST-NO**_OMRON-G5Q.kicad_mod
Relay_SANYOU_SRD_Series_**Form_C**.kicad_mod
All other relays having no specifier.
What is your advice for the naming convention ? I think xPDT (for CO contact), xPST-NC and xPST-NO could be a good convention as the contact are completely described in a single place.

Although check utility tells rule 6.3 is violated, it is correct. Pin A1 is equivalent to 1. The datasheet expressly names the coil pins A1 and A2. Also, I reused the Schrack RTD-II modules that already used A1 and A2.

Regarding your point #3. I should be able to add an alias for the Schrack relay symbols on the Finder ones as they have the same pinning.

Fred

**Comment by jkriege2** [comment]
Hi!

about the naming I would go for the standard set by the manufactrer ... About KLC 6.3 you're right (of course ;-) For the clearance, please stick to the standard of 0.25mm.

Best,
JAN

**Comment by fred-maria** [comment]
Well, I renamed module name with the contact type according to datasheet : 1-Form-A, 1-Form-B and 1-Form-C instead of the previous SPST_xxxxx_Form-A and SPST_xxxxx_Form-B.
Let me know if this is OK for you ?

**Comment by jkriege2** [comment]
Nice work, thanks a lot!
JAN

**Pull request merged**
