### PR TITLE
Add OMRON G5Q relay

### PR DESCRIPTION
**Pull request by Roman3349**
- [ ] SPST-NO
spst-no

- [ ] SPDT
spdt

- [Datasheet](https://www.omron.com/ecb/products/pdf/en-g5q.pdf)

Signed-off-by: Roman3349 <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

first of all: thanks for the contribution. Now for a closer review:
1. GENERAL: We have a set of rules for devices in this lib: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention ... so please try to follow them as good as possible. There are also util-scripts that check these rules (more or less accurately): https://github.com/KiCad/kicad-library-utils
2. About your footprints, please change the following:
  1. add a drawing of the exact outline on the F.Fab layer 0.1mm line width (most of the silkscreen can go to F.Fab, especially the contacts, as they won't be visible after soldering the component anyways.
  2. add Courtyard with 0.25mm offset from the pins/component outline, 0.15mm line width
  3. silkscreen should be visible after putting the component on the board
  4. Your footprints are flipped horizontally, NOTE that the datasheet shows BOTTOM-Views of the pins, NOT top-views!
3. As there is no symbol matching your relay (at least I didn't find any): Please also add symbols to the kicad-library ... 

Thanks and Best,
JAN

**Comment by Roman3349** [comment]
@jkriege2 Fixed!

**Comment by jkriege2** [comment]
Hi!

nice work and thanks for the work ... I spotted one mistake though:
In `Relay_SPDT_OMRON-G5Q`, pin 4 has to be moved 2.54mm to the left (see datasheet!). Please fix that ... then I'll merge!
Here's how it should look:
g5q

Best,
JAN

**Comment by Roman3349** [comment]
@jkriege2 Fixed!

**Comment by jkriege2** [comment]
nice work!

JAN

**Pull request merged**
