### PR TITLE
Fix KLC rules

### PR DESCRIPTION
**Pull request by Roman3349**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice addition/fix. I also added a PR to rename the 3D parts lib accordingly (which we can also merge when this is done): https://github.com/KiCad/kicad-library/pull/858

Since you're currently at it. Could you please also add the missing F.Fab-layer to some of the footprints?

Thanks,
JAN

**Comment by jkriege2** [comment]
Also we now updates the KLC to require a 0.12mm thick silkscreen ... could you also change that (although we can do that in a second PR).
 ... and there are some keywords separated by `,` not space ... if you have time, could you fix that?

Thank you very much!
JAN

**Comment by Roman3349** [comment]
Hi!

next week I am going to add the missing F.Fab-layer to some of the footprints.

Fixed rules:
- 6.5 - fixed a 0.12mm thick silkscreen
- 6.6 - added a 0.05mm thick courtyard
- 6.9 - fixed a 0.10mm thick fabrication layer
- 10.3 - remove comas from keywords
- 10.8 - fixed name of directory for 3D shape

**Comment by jkriege2** [comment]
Very nice! Let me know when I should have a second look!
JAN

**Comment by Roman3349** [comment]
@jkriege2 Sorry, I haven't got a time for adding the missing F.Fab-layer to some of the footprints. Please merge this pull request without it.

**Comment by jkriege2** [comment]
can do, but please rename the 3dshapes directory back to `Relays_ThroughHole.3dshapes` ... that#s technically a violation, but currently the models reside there ...

JAN

**Comment by Roman3349** [comment]
@jkriege2 Done.

**Comment by jkriege2** [comment]
Thanks!
JAN

**Pull request merged**
